#!/bin/bash
# Quick Start Script for AI Analytics Agent

cd "/Users/abhijeetrathod/AI AGENT 1"

echo "🤖 AI-Based Data Analytics Agent"
echo "=================================="
echo "✅ Environment Setup Complete"
echo ""
echo "📋 Project Details:"
echo "  - Location: /Users/abhijeetrathod/AI AGENT 1"
echo "  - Python Version: 3.11"
echo "  - Total Files: 20+"
echo "  - Module Count: 8"
echo "  - Line of Code: 2000+"
echo ""
echo "🚀 To run the application, execute:"
echo "   streamlit run app.py"
echo ""
echo "📊 Or use:"
echo "   python3 -m streamlit run app.py"
echo ""
echo "🔐 Login Credentials:"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "✨ Features:"
echo "   ✓ Secure login system"
echo "   ✓ CSV/Excel file upload"
echo "   ✓ Data cleaning & preprocessing"
echo "   ✓ Statistical analysis"
echo "   ✓ 8+ interactive visualizations"
echo "   ✓ ML models (Linear, Polynomial, Random Forest)"
echo "   ✓ Auto-generated insights"
echo "   ✓ Report generation (Excel/CSV/PDF)"
echo ""
echo "📚 Documentation:"
echo "   - README.md (comprehensive guide)"
echo "   - copilot-instructions.md (technical details)"
echo ""
echo "✅ Ready to use!"
